# Generated by Django 4.1 on 2022-11-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widthrowinfo',
            name='invest_amt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widthrowinfo',
            name='no_of_days',
            field=models.IntegerField(default=0),
        ),
    ]
